[workspace]
members = [
    "crates/medha-core",
    "crates/medha-store",
    "crates/medha-sync",
    "crates/medha",
    "crates/medha-cli",
    "crates/medha-napi",
]
resolver = "2"

[workspace.package]
version = "0.7.4"
edition = "2021"
authors = ["Nimish Phalnikar <https://github.com/nimishph>"]
license = "MIT"
repository = "https://github.com/nimishph/medha"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
