import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { durabilityFactor } from '../durability.ts';
import { emaStep } from '../ema.ts';
import { type EntityState, freshState } from '../entity.ts';
import { type Episode, foldEpisode } from '../episode.ts';
import { evaluateGates } from '../hint.ts';
import type { KindSpec } from '../kinds.ts';
import { recencyDecay } from '../recency.ts';
import { round6 } from '../rounding.ts';
import { APPLY, REJECT_CONTEXT, REJECT_RULE, type SignalSpec, SKIP } from '../signals.ts';
import { TRUST_SPEC_VERSION } from '../thresholds.ts';
import { statusFrom, trustOf } from '../trust.ts';
import { wilsonLowerBound } from '../wilson.ts';

/**
 * Conformance against docs/spec/vectors (generated by the independent Python implementation in
 * generate.py). Comparison is exact: both sides round with round6 (spec §1.1). A port passes when
 * it does the same over the same JSON.
 */

const DIR = join(import.meta.dir, '..', '..', '..', 'docs', 'spec', 'vectors');
const load = (name: string) => JSON.parse(readFileSync(join(DIR, name), 'utf8'));

const SIGNALS: Record<string, SignalSpec> = {
  APPLY,
  SKIP,
  REJECT_CONTEXT,
  REJECT_RULE,
  ADOPTED: { name: 'ADOPTED', value: 0.6, countsAsTrial: true, countsAsSuccess: true },
};

const KEY = { namespace: 'n', kind: 'rule', id: 'r' };

interface Step {
  signal?: string;
  ok?: boolean;
  kind?: string;
  at: number;
  anchors?: [string, string][];
  author?: string;
}

describe('conformance vectors', () => {
  const components = load('components.json');
  const scenarios = load('scenarios.json');

  test('vectors target the kernel spec version', () => {
    expect(components.specVersion).toBe(TRUST_SPEC_VERSION);
    expect(scenarios.specVersion).toBe(TRUST_SPEC_VERSION);
  });

  test('round6', () => {
    for (const v of components.round6) expect(round6(v.input)).toBe(v.expected);
  });

  test('wilsonLower', () => {
    for (const v of components.wilsonLower) expect(wilsonLowerBound(v.k, v.n)).toBe(v.expected);
  });

  test('recency', () => {
    for (const v of components.recency) {
      expect(recencyDecay(v.lastUsedAt, v.now, v.config)).toBe(v.expected);
    }
  });

  test('durability', () => {
    for (const v of components.durability) expect(durabilityFactor(v.h)).toBe(v.expected);
  });

  test('emaStep', () => {
    for (const v of components.emaStep) {
      expect(emaStep(v.mu ?? undefined, v.signal, v.alpha)).toBe(v.expected);
    }
  });

  for (const scn of scenarios.scenarios) {
    test(`scenario: ${scn.name}`, () => {
      const kindSpec: KindSpec = { name: 'rule', ...(scn.kindSpec ?? {}) };
      let state = freshState(KEY, 0, {
        theta0: scn.theta0 ?? 0.5,
        guard: { kind: scn.guardKind ?? 'none', lastOk: null, lastOkAt: null },
      });
      let seq = 0;
      for (const step of scn.steps as Step[]) {
        const base = { seq: ++seq, key: KEY, at: step.at, ensure: true };
        const episode: Episode =
          step.ok !== undefined
            ? { ...base, type: 'guard', ok: step.ok, ...(step.kind ? { kind: step.kind } : {}) }
            : {
                ...base,
                type: 'signal',
                spec: SIGNALS[step.signal as string] as SignalSpec,
                ...(step.author !== undefined ? { author: step.author } : {}),
                ...(step.anchors
                  ? { anchors: step.anchors.map(([kind, value]) => ({ kind, value })) }
                  : {}),
              };
        state = foldEpisode(state, episode, { kindSpec }) as EntityState;
      }

      const result = trustOf(state, scn.now, kindSpec);
      const [trusted, active, drifting] = evaluateGates(state, result.trust, kindSpec);
      const want = scn.expected;
      expect(result.trust).toBe(want.trust);
      expect(result.components).toEqual(want.components);
      expect(statusFrom(state, result, kindSpec)).toBe(want.status);
      expect(state.status).toBe(want.storedStatus);
      expect({ trusted: trusted.met, active: active.met, drifting: drifting.met }).toEqual(
        want.gates,
      );
      expect(drifting.value).toBe(want.driftDelta);
      expect(drifting.met).toBe(want.isDrifting);
      expect(state.evidence).toEqual(want.evidence);
      expect(state.ema.mu).toBe(want.ema.mu);
      expect(state.authors ?? {}).toEqual(want.authors);
    });
  }
});
