/**
 * Generates `site/integrations.md` from the declarative MCP client registry
 * (`cli/src/integrations/clients.json`), the same source `medha mcp config` renders from.
 *
 * Why generate: five clients × two launchers × per-scope paths is exactly the surface a hand-written
 * page lets drift. The registry already carries the snippets, scope tables, docs URLs and per-client
 * notes; this page is that data laid out for humans, so the docs and `medha mcp config` cannot
 * disagree.
 *
 * Run with bun (`bun run gen:integrations`) — it needs TypeScript sources that resolve through the
 * workspace. The rendering logic is a pure function of the report shapes (exported, no workspace
 * import needed to exercise it), mirroring `gen-cli-ref.ts`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import type {
  McpConfigListReport,
  McpConfigSnippetReport,
} from '../../cli/src/integrations/mcp-config.ts';

export interface IntegrationsPageInput {
  readonly list: McpConfigListReport;
  /** One entry per `list.clients`, in the same order: default scope, PATH launcher. */
  readonly primary: readonly McpConfigSnippetReport[];
  /** One entry per `list.clients`, in the same order: default scope, npx launcher. */
  readonly pinned: readonly McpConfigSnippetReport[];
  /** `registry.launchers.npx.argv` — the global no-install launcher example. */
  readonly npxArgv: readonly string[];
}

function jsonBlock(text: string): string[] {
  return ['```json', text.trimEnd(), '```'];
}

/** The registry wraps every server in its client's container; the docs table only needs the file. */
function scopeTable(client: McpConfigListReport['clients'][number]): string[] {
  const lines = ['| Scope | Config file |', '| --- | --- |'];
  for (const scope of client.scopes) {
    lines.push(`| \`${scope.id}\` | \`${scope.path}\` |`);
  }
  return lines;
}

/** Render the whole page body. Exported so it can be exercised against stub reports. */
export function renderIntegrationsPage(input: IntegrationsPageInput): string {
  const [command, ...rest] = input.npxArgv;
  if (command === undefined) {
    throw new Error('the npx launcher argv is empty');
  }
  const lines: string[] = [
    '<!-- Generated by site/scripts/gen-integrations.ts from cli/src/integrations/clients.json.',
    '     Do not edit. Run `bun run gen:integrations` in site/. -->',
    '',
    '# Connect an MCP client',
    '',
    'medha speaks MCP on stdio: no daemon, no port, no background process. The server runs inside',
    'the host that launches it and reads the engine home in the working directory like any other',
    'command. Every snippet on this page is generated from the same registry that powers',
    '`medha mcp config`, so the page and the command cannot disagree.',
    '',
    'Two things hold whichever client you use:',
    '',
    '- **Initialize the project first.** Run `medha init` once; the server refuses to start without',
    '  an engine home.',
    '- **Pick one of the two launchers**, shown for every client below.',
    '',
    '## The two launchers',
    '',
    '### On your PATH',
    '',
    'Install the CLI globally (`npm install --global @cntxt-labs/medha-cli`) and the entry is a bare',
    'command — one install, every project:',
    '',
    ...jsonBlock(JSON.stringify({ command: 'medha', args: ['mcp', 'serve'] }, null, 2)),
    '',
    '### Pinned npx, no install',
    '',
    'Every launch runs the exact published version — nothing to install or upgrade:',
    '',
    ...jsonBlock(JSON.stringify({ command, args: rest }, null, 2)),
    '',
    '## Per-client configuration',
    '',
  ];
  for (const [index, client] of input.list.clients.entries()) {
    const primary = input.primary[index];
    const pinned = input.pinned[index];
    if (primary === undefined || pinned === undefined) continue;
    lines.push(`### ${client.name}`, '');
    lines.push(`CLI id: \`${client.id}\` — docs: ${client.docs}`, '');
    lines.push(...scopeTable(client), '');
    lines.push('With the PATH launcher:', '');
    lines.push(...jsonBlock(primary.text), '');
    lines.push('With the pinned npx launcher:', '');
    lines.push(...jsonBlock(pinned.text), '');
    if (client.notes !== undefined) {
      lines.push(`> ${client.notes}`, '');
    }
  }
  lines.push(
    '## The Claude Code plugin',
    '',
    'Claude Code users can skip the file editing entirely: add the cntxt-labs marketplace and',
    'install the medha plugin. It bundles the MCP server (pinned npx launcher), the agent skill, and',
    '`/medha:` slash commands for the read side (`status`, `hints`, `drift`, `pack`).',
    '',
    '```sh',
    '/plugin marketplace add nimishph/cntxt-labs',
    '/plugin install medha@cntxt-labs',
    '```',
    '',
    'The same two steps work from the shell as `claude plugin marketplace add nimishph/cntxt-labs`',
    'and `claude plugin install medha@cntxt-labs`. The bundled server still needs `medha init` in',
    'the project, exactly like every snippet above.',
    '',
    '## Do it from the CLI',
    '',
    'The page above is what these commands print:',
    '',
    '```sh',
    'medha mcp config --list            # clients, scopes, launchers',
    'medha mcp config cursor            # print the snippet',
    'medha mcp config cursor --write    # merge it into the scope file',
    'medha mcp config --all             # every client at once',
    '```',
    '',
    '`--write` merges beside whatever the file already holds: other servers and unrelated settings',
    'survive untouched, and re-running it reports `no change` rather than rewriting the file.',
    '',
    '## Next',
    '',
    '- [Using it from an agent](/guide/mcp) — the tools behind the server, and how to prompt with them.',
    '- [CLI reference](/cli) — every command, including `medha mcp config`.',
    '',
  );
  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()}\n`;
}

const OUTPUT = new URL('../integrations.md', import.meta.url);

if (import.meta.main === true) {
  // Imported dynamically so the renderer above stays importable without the workspace installed.
  // bun is required: the sources are TypeScript resolving through workspace paths.
  const { loadRegistry } = await import('../../cli/src/integrations/registry.ts');
  const { runMcpConfigAll, runMcpConfigList } = await import(
    '../../cli/src/integrations/mcp-config.ts'
  );
  const { VERSION_PLACEHOLDER } = await import('../../cli/src/integrations/render.ts');
  const { VERSION } = await import('../../cli/src/version.ts');
  const registry = loadRegistry();
  const npxArgv = registry.launchers.npx?.argv;
  if (npxArgv === undefined) {
    throw new Error("the registry declares no 'npx' launcher");
  }
  const markdown = renderIntegrationsPage({
    list: runMcpConfigList(registry),
    primary: runMcpConfigAll(registry, { launcherId: 'path' }),
    pinned: runMcpConfigAll(registry, { launcherId: 'npx' }),
    // Launcher argv carries the raw placeholder; resolve it exactly as renderServerEntry does.
    npxArgv: npxArgv.map((part) => part.replaceAll(VERSION_PLACEHOLDER, VERSION)),
  });
  await mkdir(new URL('./', OUTPUT), { recursive: true });
  await writeFile(OUTPUT, markdown, 'utf8');
  console.log(`wrote ${OUTPUT.pathname}`);
}
